name: app_mdm
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  objectbox: ^2.0.0
  objectbox_flutter_libs: any
 
  
  # For ObjectBox Sync this dependency should appear instead:
  # objectbox_sync_flutter_libs: any  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  objectbox_generator: any

flutter:
  uses-material-design: true
  assets: 
    - assets/img/
